features:
  - Dst_Port
  - Src_Port
  - TotLen_Bwd_Pkts
  - Flow_Byts/s
  - Fwd_Pkt_Len_Max
  - TotLen_Fwd_Pkts
  - Bwd_Pkt_Len_Max
  - Pkt_Len_Min
  - Flow_Duration
  - Flow_Pkts/s
  - Init_Bwd_Win_Byts
  - Flow_IAT_Mean
  - Bwd_Pkts/s
  - Bwd_Header_Len
  - Protocol
  - Fwd_IAT_Mean
  - Fwd_IAT_Tot
  - Flow_IAT_Std
  - Bwd_IAT_Tot
  - Tot_Fwd_Pkts
  - Pkt_Len_Std
  - Bwd_IAT_Mean
  - Fwd_IAT_Std
  - Tot_Bwd_Pkts
  - Bwd_Pkt_Len_Std
  - Fwd_Pkt_Len_Std
  - Bwd_IAT_Std
  - Active_Mean
  - Active_Min
  - Init_Fwd_Win_Byts
  - Down/Up_Ratio
  - Active_Std
  - Bwd_PSH_Flags
  - Bwd_Pkts/b_Avg
  - ECE_Flag_Cnt
  - Fwd_Seg_Size_Min
  - Fwd_PSH_Flags
  - FIN_Flag_Cnt
  - Bwd_URG_Flags
  - Fwd_URG_Flags
  - SYN_Flag_Cnt
  - Fwd_Blk_Rate_Avg
  - Bwd_Byts/b_Avg
  - Fwd_Byts/b_Avg
  - RST_Flag_Cnt
  - CWE_Flag_Count
  - Fwd_Pkts/b_Avg
  - Bwd_Blk_Rate_Avg
